### PR TITLE
Add initial draft for bulk query endpoint

### PR DESCRIPTION
**Pull request by GeorgDangl**
Hey guys,

as discussed, here's a first idea how the bulk query endpoint could be added to the API. Looking forwards to your input😀

CC @pasi-paasiala @ykulbak @jasollien

### CODE REVIEW

**Comment by ykulbak** [comment]
I suggest adding a UTC timestamp query parameter `since` that would request the server to only return versions that were created on or after that timestamp. This should be easy for clients since all they need to do is provide the last polling time and would, I believe, reduce implementation complexity for the servers.

**Comment by ykulbak** [comment]
Did you deliberately choose a flat list of versions rather than grouping the versions of each document together?

**Comment by GeorgDangl** [comment]
> Did you deliberately choose a flat list of versions rather than grouping the versions of each document together?

Yeah, that was on purpose. My reasoning was to just return a flat list, containing the _latest_ version for each queried document. We could also nest it deeper by `document_id`, but I thought the flat list fits well here.

**Comment by GeorgDangl** [comment]
> I suggest adding a UTC timestamp query parameter `since` that would request the server to only return versions that were created on or after that timestamp. This should be easy for clients since all they need to do is provide the last polling time and would, I believe, reduce implementation complexity for the servers.

Sounds good, added with 2c7c3c71326c493cf84a37d858426414321b7588

**Comment by GeorgDangl** [comment]
We've made some more changes during the call today, but we're not finished yet. We will look at it again next Monday😀

**Pull request merged**
